[project]
name = "section13"
version = "0.1.0"
description = "CIFAR-10 image classification experiments"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "flask>=2.0.0",
    "numpy>=1.21.0",
    "pillow>=8.0.0",
]
