[project]
name = "section13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=2.0.0",
    "numpy>=1.21.0",
    "pillow>=8.0.0",
    "tensorflow>=2.13.0",
]
